export const sectorConfig: Record<string, { color: string; bg: string; gradient: string; accent: string }> = {
  Retail:        { color: 'text-emerald-700', bg: 'bg-emerald-50 border-emerald-200', gradient: 'from-emerald-600 to-teal-700', accent: '#059669' },
  Finance:       { color: 'text-blue-700',    bg: 'bg-blue-50 border-blue-200',       gradient: 'from-blue-600 to-indigo-700', accent: '#2563EB' },
  'Oil & Gas':   { color: 'text-orange-700',  bg: 'bg-orange-50 border-orange-200',   gradient: 'from-orange-500 to-amber-600', accent: '#D97706' },
  Industrial:    { color: 'text-slate-700',   bg: 'bg-slate-50 border-slate-200',     gradient: 'from-slate-600 to-gray-700', accent: '#475569' },
  Government:    { color: 'text-purple-700',  bg: 'bg-purple-50 border-purple-200',   gradient: 'from-purple-600 to-indigo-700', accent: '#7C3AED' },
  'Real Estate': { color: 'text-amber-700',   bg: 'bg-amber-50 border-amber-200',     gradient: 'from-amber-500 to-orange-600', accent: '#D97706' },
  Transport:     { color: 'text-cyan-700',    bg: 'bg-cyan-50 border-cyan-200',       gradient: 'from-cyan-600 to-blue-700', accent: '#0891B2' },
  Telecom:       { color: 'text-indigo-700',  bg: 'bg-indigo-50 border-indigo-200',   gradient: 'from-indigo-600 to-blue-700', accent: '#4F46E5' },
  Automotive:    { color: 'text-violet-700',  bg: 'bg-violet-50 border-violet-200',   gradient: 'from-violet-600 to-purple-700', accent: '#7C3AED' },
}

export const caseStudies = [
  // ── Retail & Food ──
  {
    id: 'cs-01',
    sector: 'Retail',
    image: '/images/case-grocery-network.jpg',
    title: 'Identifying Potential Locations to Expand a Grocery Store Network',
    geography: 'Dubai and Abu Dhabi, UAE',
    segment: 'Grocery shops, Consumers',
    methodology: 'Qualitative IDIs: 20+ · Quantitative Interviews: 500+ · Secondary research',
    stats: [{ label: 'IDIs Conducted', value: '20+' }, { label: 'Interviews', value: '500+' }, { label: 'Cities', value: '2' }, { label: 'Clusters Mapped', value: '40+' }],
    challenge: 'A diversified business group needed to expand their retail operations. Key questions: Which locations are most attractive? How many stores? What store format? What product mix? What is the competitive landscape?',
    approach: '4BC conducted a thorough geo-mapping exercise dividing cities into clusters, plotting retail stores, and understanding the demographic profile of residents and their grocery shopping habits. High-attractiveness clusters were identified using the proprietary 4BC Landscape tool.',
    outcome: 'The client expanded their retail operations across high-attractive clusters across each of the cities, with a data-backed network plan guiding store format and product assortment decisions.',
    clientLogo: '/logos/01_Retail_and_Food/bmmi.png',
  },
  {
    id: 'cs-03',
    sector: 'Retail',
    image: '/images/case-horeca-oils.jpg',
    title: 'Usage & Attitudes of HORECA Towards Oils in Saudi Arabia',
    geography: 'Saudi Arabia (Riyadh, Jeddah, Dammam)',
    segment: 'HORECA',
    methodology: 'Quantitative Interviews: 300+',
    stats: [{ label: 'Interviews', value: '300+' }, { label: 'Cities', value: '3' }, { label: 'Brands Tracked', value: '10+' }, { label: 'KPIs Measured', value: '3' }],
    challenge: 'A leading FMCG company needed to develop a successful growth strategy in the HORECA segment by understanding their needs and expectations in the "oil" category.',
    approach: 'Large sample quantitative research across HORECA in Saudi Arabia to understand purchase habits, brand awareness, and sourcing practices across key cities.',
    outcome: 'The client penetrated further into the HORECA segment for oils and fats by offering the right packaging and SKUs, informed by granular demand data.',
    clientLogo: '/logos/01_Retail_and_Food/freshly-foods.png',
  },
  {
    id: 'cs-09',
    sector: 'Retail',
    image: '/images/case-plant-based-food.png',
    title: 'Concept Evaluation for Plant-Based Food Products in UAE',
    geography: 'UAE',
    segment: 'General consumers, Health-conscious consumers',
    methodology: 'Qualitative Focus Groups: 6+ · Quantitative Interviews: 300+',
    stats: [{ label: 'Focus Groups', value: '6+' }, { label: 'Interviews', value: '300+' }, { label: 'Nationalities Covered', value: '5+' }, { label: 'Concepts Tested', value: '3' }],
    challenge: 'A food manufacturer was evaluating a new range of plant-based products and needed to understand consumer awareness, attitudes, and purchase intent in the UAE market before committing to a full launch.',
    approach: 'Multi-phase research combining qualitative focus groups to explore initial perceptions and refine concepts, followed by quantitative validation across 300+ consumers from diverse nationalities.',
    outcome: 'The client refined product formulations and packaging based on consumer feedback, enabling a successful market launch aligned to actual consumer expectations.',
    clientLogo: null,
  },
  {
    id: 'cs-10',
    sector: 'Retail',
    image: '/images/case-premium-tea.jpg',
    title: 'Channel Research for Premium Tea Across HORECA in UAE',
    geography: 'UAE',
    segment: 'HORECA operators — Hotels, Cafés, Restaurants',
    methodology: 'Qualitative IDIs: 30+',
    stats: [{ label: 'IDIs Conducted', value: '30+' }, { label: 'HORECA Types', value: '3' }, { label: 'Brands Tracked', value: '8+' }, { label: 'Distribution Channels', value: '4' }],
    challenge: 'A premium tea brand needed to understand how hotels, cafés, and restaurants select and source premium teas in the UAE, and to identify optimal routes to market.',
    approach: 'In-depth interviews with F&B decision-makers and purchasing managers across different HORECA formats to map procurement processes, brand preferences, and willingness to trade up.',
    outcome: 'The client developed a tailored HORECA go-to-market strategy, identifying the most receptive segments and the most effective distribution approach for premium teas.',
    clientLogo: null,
  },
  {
    id: 'cs-11',
    sector: 'Retail',
    image: '/images/case-tea-market.jpg',
    title: 'Market Sizing and Opportunity Assessment of Tea in Egypt and Pakistan',
    geography: 'Egypt and Pakistan',
    segment: 'General consumers, Trade channels',
    methodology: 'Quantitative Interviews: 600+ · Secondary Research',
    stats: [{ label: 'Interviews', value: '600+' }, { label: 'Countries', value: '2' }, { label: 'Segments Mapped', value: '5+' }, { label: 'Channels Studied', value: '4' }],
    challenge: 'A global beverage company needed to estimate the size and structure of the tea market in Egypt and Pakistan to inform its regional growth strategy.',
    approach: 'Combined secondary data analysis with primary consumer and trade research to quantify demand by segment, channel, and geography — identifying key growth pockets in each market.',
    outcome: 'The client identified the highest-potential segments and distribution channels in both markets, directly informing their market entry investment priorities.',
    clientLogo: null,
  },
  {
    id: 'cs-12',
    sector: 'Retail',
    image: '/images/case-salad-dressings.jpg',
    title: 'Need State Assessment of Salad Dressings Across HORECA in UAE',
    geography: 'UAE',
    segment: 'HORECA operators — Chefs, F&B Purchasers',
    methodology: 'Qualitative IDIs: 40+',
    stats: [{ label: 'IDIs Conducted', value: '40+' }, { label: 'HORECA Formats', value: '4' }, { label: 'Need States Identified', value: '6+' }, { label: 'Brands Tracked', value: '10+' }],
    challenge: 'An FMCG company wanted to understand how salad dressings are purchased, used, and perceived across HORECA operators in the UAE to develop a focused growth strategy.',
    approach: 'Qualitative in-depth interviews with chefs and F&B purchasers across hotels, restaurants, and cafeterias to uncover need states, usage occasions, and unmet needs.',
    outcome: 'The client repositioned their dressing range and developed targeted HORECA SKUs, resulting in stronger penetration among food service operators.',
    clientLogo: null,
  },
  {
    id: 'cs-13',
    sector: 'Retail',
    image: '/images/case-ready-to-eat.jpg',
    title: 'Market Assessment for Ready-to-Eat Food Products in Bahrain',
    geography: 'Bahrain',
    segment: 'General consumers, Modern trade buyers',
    methodology: 'Quantitative Interviews: 200+ · Secondary Research',
    stats: [{ label: 'Interviews', value: '200+' }, { label: 'Consumer Segments', value: '3' }, { label: 'Channels Studied', value: '4' }, { label: 'Competitor Brands', value: '10+' }],
    challenge: 'A regional food company wanted to assess the size and attractiveness of the ready-to-eat food market in Bahrain before committing to a new product launch.',
    approach: 'Quantitative consumer survey combined with trade interviews and secondary data to estimate market size, understand competitive dynamics, and identify demand gaps.',
    outcome: 'The client validated the market opportunity and launched a targeted range focused on working expat segments with the highest purchase intent.',
    clientLogo: null,
  },

  // ── Real Estate ──
  {
    id: 'cs-08',
    sector: 'Real Estate',
    image: '/images/case-free-zones.jpg',
    title: 'Competitive Market Intelligence Study on Various Free Zones in the UAE',
    geography: 'UAE',
    segment: 'Offices, Industrial Units, Land, Flexi Desk',
    methodology: 'Mystery Calls: 50+ · Secondary Research',
    stats: [{ label: 'Free Zones Studied', value: '15+' }, { label: 'Mystery Calls', value: '50+' }, { label: 'Offer Types', value: '4' }, { label: 'Research Methods', value: '2' }],
    challenge: 'A prominent government-owned free zone authority needed to understand the competition offerings and conduct a benchmarking competitive intelligence study.',
    approach: '4BC conducted desk research along with mystery calls to free zones to understand offerings and prices across all key property categories.',
    outcome: 'The client developed their offerings to be competitive in the local UAE market.',
    clientLogo: '/logos/03_Real_Estate_and_Construction/dmcc.png',
  },
  {
    id: 'cs-14',
    sector: 'Real Estate',
    image: '/images/case-mall-catchment.jpg',
    title: 'Catchment Area Assessment for Developing a New Mall in UAE',
    geography: 'UAE',
    segment: 'General consumers, Residential communities',
    methodology: 'Geo-mapping (4BC Landscape) · Quantitative Intercept Surveys: 400+ · Secondary Research',
    stats: [{ label: 'GPS Points Mapped', value: '500+' }, { label: 'Consumer Surveys', value: '400+' }, { label: 'Catchment Zones', value: '3' }, { label: 'Competitor Malls', value: '10+' }],
    challenge: 'A real estate developer needed to assess whether a proposed mall location had sufficient catchment, spending potential, and competitive positioning to justify a significant capital investment.',
    approach: '4BC Landscape was used to map demographics, population density, and competitive retail within defined catchment radii, supplemented by intercept surveys among area residents to understand shopping habits and unmet needs.',
    outcome: 'The developer received a clear go/no-go recommendation with supporting data on projected footfall, optimal tenant mix, and competitive differentiation strategies.',
    clientLogo: null,
  },
  {
    id: 'cs-15',
    sector: 'Real Estate',
    image: '/images/case-pedestrian-dubai.jpg',
    title: 'Walking Habits and Pedestrian Flow Study in Dubai',
    geography: 'Dubai, UAE',
    segment: 'General consumers, Pedestrians',
    methodology: 'Observational Research · Quantitative Surveys: 500+ · Secondary Research',
    stats: [{ label: 'Survey Respondents', value: '500+' }, { label: 'Locations Studied', value: '8+' }, { label: 'Time Periods', value: '4' }, { label: 'Data Points Collected', value: '10K+' }],
    challenge: 'A real estate developer needed to understand pedestrian traffic patterns, walking motivations, and perceptions of walkability in key Dubai neighborhoods to inform urban planning and retail positioning.',
    approach: 'Combined observational research at key pedestrian areas with large-sample quantitative surveys to map walking behaviors, route preferences, barriers to walking, and perceptions of the urban environment.',
    outcome: 'The client used findings to optimize the design and positioning of their development, ensuring strong pedestrian connectivity and retail appeal.',
    clientLogo: null,
  },
  {
    id: 'cs-16',
    sector: 'Real Estate',
    image: '/images/case-free-zones.jpg',
    title: 'Campaign Recall and Effectiveness Study for a UAE Free Zone',
    geography: 'UAE',
    segment: 'Business owners, Decision makers, SMEs',
    methodology: 'Quantitative Interviews: 300+ · Mystery Calls: 20+',
    stats: [{ label: 'Interviews', value: '300+' }, { label: 'Mystery Calls', value: '20+' }, { label: 'Campaigns Evaluated', value: '4+' }, { label: 'Channels Assessed', value: '6' }],
    challenge: 'A government-owned free zone needed to evaluate the effectiveness of their marketing campaigns across different channels and understand which messages were driving awareness and enquiries.',
    approach: 'Quantitative study among SME decision-makers to measure unaided and aided campaign recall, message association, and channel attribution — supplemented by mystery calls to assess sales team performance.',
    outcome: 'The free zone reallocated marketing budgets toward higher-performing channels and refreshed messaging based on what was and wasn\'t cutting through to their target audience.',
    clientLogo: null,
  },
  {
    id: 'cs-17',
    sector: 'Real Estate',
    image: '/images/case-building-automation.jpg',
    title: 'Growth Strategy for Building Automation Solutions in UAE',
    geography: 'UAE',
    segment: 'Building owners, Facility managers, Developers',
    methodology: 'Qualitative IDIs: 30+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '30+' }, { label: 'Building Segments', value: '4' }, { label: 'Competitor Brands', value: '8+' }, { label: 'Strategy Horizon', value: '5 Yrs' }],
    challenge: 'A building automation company wanted to assess the growth potential of the UAE market and develop a strategy to expand their footprint across commercial, hospitality, and residential segments.',
    approach: 'Expert in-depth interviews with building owners, developers, and facility management companies, combined with secondary research to size the opportunity and map the competitive landscape.',
    outcome: 'The client identified the highest-growth segments and developed a prioritized go-to-market approach targeting key influencers in the building automation procurement cycle.',
    clientLogo: null,
  },

  // ── Industrial & Manufacturing ──
  {
    id: 'cs-04',
    sector: 'Industrial',
    image: '/images/case-channel-strategy.jpg',
    title: 'Develop Channel Strategy for a Large Business Group in UAE',
    geography: 'UAE',
    segment: 'Dealers, Consumers',
    methodology: 'Qualitative IDIs: 100+ · Quantitative Interviews: 4,500+ · Secondary Research · Geo-mapping',
    stats: [{ label: 'Expert IDIs', value: '100+' }, { label: 'Interviews', value: '4,500+' }, { label: 'GPS Locations', value: '1,500+' }, { label: 'Strategy Horizon', value: '5 Yrs' }],
    challenge: 'One of the largest business Groups in UAE wanted to understand the channel network for all its offerings across automobile, industrial equipment, and services.',
    approach: '4BC used the geo-mapping platform to understand demographics, conducted 100+ Expert IDIs, and mapped 1,500+ GPS locations along with comprehensive secondary data to build a full channel intelligence picture.',
    outcome: 'The client developed a 5-year network strategy for their entire portfolio based on the findings.',
    clientLogo: null,
  },
  {
    id: 'cs-06',
    sector: 'Industrial',
    image: '/images/case-concrete-pipe.jpg',
    title: 'Market Feasibility for Setting Up a Concrete Pipe Manufacturing Unit in Oman',
    geography: 'UAE, Oman and Saudi Arabia',
    segment: 'Manufacturers, EPC Consultants and Contractors',
    methodology: 'Qualitative IDIs: 50+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '50+' }, { label: 'Markets', value: '3' }, { label: 'Pipeline Segments', value: '2' }, { label: 'Target Groups', value: '3' }],
    challenge: 'A large Omani Group needed to understand the market potential for concrete pipe business in Oman and its export opportunity to neighboring countries.',
    approach: '4BC conducted competition landscape, market sizing, market share, and market forecast analysis for sewage pipelines and storm water drainage pipelines.',
    outcome: 'The client started operations of manufacturing concrete pipes in Muscat, Oman, targeting Oman, UAE and Saudi Arabia.',
    clientLogo: '/logos/04_Industrial/amiantit-oman.png',
  },
  {
    id: 'cs-18',
    sector: 'Industrial',
    image: '/images/case-construction-equipment.jpg',
    title: 'Market Sizing and Competitive Landscape for Construction Equipment in UAE',
    geography: 'UAE',
    segment: 'Contractors, Equipment dealers, Rental companies',
    methodology: 'Qualitative IDIs: 40+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '40+' }, { label: 'Equipment Categories', value: '8+' }, { label: 'Competitor Brands', value: '15+' }, { label: 'Market Horizon', value: '5 Yrs' }],
    challenge: 'A global construction equipment manufacturer needed to understand the size, structure, and competitive dynamics of the UAE market ahead of a significant strategic investment.',
    approach: 'Expert interviews with contractors, dealers, and rental operators across UAE, combined with secondary data analysis to estimate market size by equipment category and identify key competitive players.',
    outcome: 'The client developed a market entry strategy focused on identified high-growth segments and underserved sub-categories within the UAE construction equipment market.',
    clientLogo: null,
  },
  {
    id: 'cs-19',
    sector: 'Industrial',
    image: '/images/case-fire-safety.jpg',
    title: 'Market Research for Fire Extinguisher Products in UAE',
    geography: 'UAE',
    segment: 'Distributors, Facilities managers, End users',
    methodology: 'Qualitative IDIs: 30+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '30+' }, { label: 'Segments Covered', value: '3' }, { label: 'Competitor Brands', value: '10+' }, { label: 'Product Types', value: '5+' }],
    challenge: 'A manufacturer of fire safety products needed to understand the UAE market landscape for fire extinguishers — including market sizing, competitive positioning, and distribution dynamics.',
    approach: 'IDIs with distributors, facilities management companies, and end users, supplemented by secondary data to size the market and map the competitive landscape.',
    outcome: 'The client prioritized specific product segments and channels for market focus, equipped with clear data on demand levels and competitive positioning.',
    clientLogo: null,
  },
  {
    id: 'cs-20',
    sector: 'Industrial',
    image: '/images/case-wood-paints.jpg',
    title: 'Market Study for Wood Paints and Coatings Across GCC',
    geography: 'GCC (UAE, Saudi Arabia, Qatar, Kuwait)',
    segment: 'Contractors, Painters, Retailers, Specifiers',
    methodology: 'Qualitative IDIs: 40+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '40+' }, { label: 'GCC Markets', value: '4' }, { label: 'Competitor Brands', value: '12+' }, { label: 'Segments Covered', value: '4' }],
    challenge: 'A leading paints manufacturer wanted to understand the wood coatings market across the GCC — sizing the opportunity, understanding channel dynamics, and assessing competitive positioning.',
    approach: 'Interviews with contractors, painters, and trade outlets across key GCC markets, combined with secondary research to size the market and estimate competitive brand shares.',
    outcome: 'The client identified the most attractive GCC markets and distribution channels for their wood coatings range, informing their regional expansion strategy.',
    clientLogo: null,
  },

  // ── Transport & Logistics ──
  {
    id: 'cs-02',
    sector: 'Transport',
    image: '/images/case-minibus-new.png',
    title: 'Opportunity Assessment of Digitalization of Minibus Taxis in South Africa',
    geography: 'South Africa',
    segment: 'Commuters, Taxi Owners, Taxi Associations, Taxi Financiers',
    methodology: 'Qualitative IDIs: 50+ · Quantitative Interviews: 500+',
    stats: [{ label: 'IDIs Conducted', value: '50+' }, { label: 'Interviews', value: '500+' }, { label: 'Stakeholder Groups', value: '4' }, { label: 'Methods Used', value: '2' }],
    challenge: 'A leading card payment company wanted to develop a solution to digitalize the ticketing system among minibus taxis in South Africa by understanding the opportunity size, drivers, and barriers.',
    approach: '4BC conducted an opportunity sizing analysis by estimating mini-bus taxis operating in South Africa, along with large sample quantitative and qualitative in-depth interviews with drivers, passengers, taxi associations and government authorities.',
    outcome: '4BC recommended a go-to-market strategy based on findings and a phase-wise roll-out plan for successful implementation.',
    clientLogo: '/logos/02_Banking_and_Finance/visa.png',
  },
  {
    id: 'cs-21',
    sector: 'Transport',
    image: '/images/case-truck-tyres.jpg',
    title: 'Market Sizing and Dealer Optimization for Truck and Bus Tyres',
    geography: 'UAE, Saudi Arabia and Egypt',
    segment: 'Fleet operators, Dealers, Distributors',
    methodology: 'Qualitative IDIs: 60+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '60+' }, { label: 'Markets Covered', value: '3' }, { label: 'Dealer Touchpoints', value: '50+' }, { label: 'Segments Mapped', value: '4' }],
    challenge: 'A global tyre manufacturer needed to understand the truck and bus tyre market across three key MEA markets and optimize their dealer network strategy.',
    approach: '4BC conducted expert IDIs with fleet operators and dealers across UAE, Saudi Arabia, and Egypt, supplemented by secondary analysis to size the market by segment and map the competitive landscape.',
    outcome: 'The client restructured their dealer network and prioritized market segments based on demand data, improving channel coverage and commercial performance.',
    clientLogo: '/logos/06_Logistics_and_Transportation/bridgestone.png',
  },
  {
    id: 'cs-23',
    sector: 'Transport',
    image: '/images/case-used-cars.jpg',
    title: 'Industry Landscape of the Used Car Market Across UAE, Afghanistan, DRC and Yemen',
    geography: 'UAE, Afghanistan, DRC and Yemen',
    segment: 'Dealers, Car buyers, Auction operators',
    methodology: 'Qualitative IDIs: 50+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '50+' }, { label: 'Markets Covered', value: '4' }, { label: 'Supply Chain Nodes', value: '5+' }, { label: 'Trade Channels', value: '6+' }],
    challenge: 'A regional automotive group wanted to understand the structure, dynamics, and opportunity in the used car market across key MEA markets — from the UAE\'s formal dealership model to informal trade in frontier markets.',
    approach: 'Expert IDIs with dealers, auctioneers, buyers, and market participants across all four markets, combined with secondary research to size markets and map trade flows.',
    outcome: 'The client identified the most commercially attractive entry points and developed market-specific strategies suited to the differing levels of formalization across markets.',
    clientLogo: null,
  },
  {
    id: 'cs-24',
    sector: 'Transport',
    image: '/images/case-seaport.jpg',
    title: 'Competitive Intelligence on Port Management and Operations Across the Middle East',
    geography: 'Middle East',
    segment: 'Port operators, Shipping companies, Logistics providers',
    methodology: 'Qualitative IDIs: 40+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '40+' }, { label: 'Ports Covered', value: '15+' }, { label: 'Markets Studied', value: '6+' }, { label: 'Segments Mapped', value: '4' }],
    challenge: 'A global port management company sought to understand the competitive landscape of port operations across the Middle East ahead of potential expansion and partnership decisions.',
    approach: 'Expert IDIs with port operators, shipping lines, and logistics providers, supplemented by extensive secondary data to map capacity, competitive dynamics, and investment trends.',
    outcome: 'The client identified priority markets for partnership and expansion, with clear intelligence on competitive positioning and regulatory considerations.',
    clientLogo: '/logos/03_Real_Estate_and_Construction/dp-world.jpeg',
  },

  // ── Automotive ──
  {
    id: 'cs-22',
    sector: 'Automotive',
    image: '/images/case-connected-car.jpg',
    title: 'Brand Positioning and Usage of Connected Car Services in UAE and Saudi Arabia',
    geography: 'UAE and Saudi Arabia',
    segment: 'Car owners, Fleet managers',
    methodology: 'Quantitative Interviews: 400+ · Secondary Research',
    stats: [{ label: 'Interviews', value: '400+' }, { label: 'Markets Covered', value: '2' }, { label: 'Services Tracked', value: '10+' }, { label: 'Segments Studied', value: '4' }],
    challenge: 'A connected car services provider needed to understand brand awareness, usage patterns, and competitive perceptions among car owners in the UAE and Saudi Arabia.',
    approach: 'Large-sample quantitative research with car owners across both markets to map awareness, trial, usage frequency, and the key drivers and barriers of service adoption.',
    outcome: 'The client refined their positioning and go-to-market strategy, focusing on the segments with highest adoption propensity and addressing identified barriers to conversion.',
    clientLogo: null,
  },

  // ── Oil & Gas ──
  {
    id: 'cs-07',
    sector: 'Oil & Gas',
    image: '/images/case-oilgas.jpg',
    title: 'Customer Satisfaction Study for a Major O&G Business in the UAE',
    geography: 'UAE',
    segment: 'Decision makers among customer companies',
    methodology: 'Quantitative Interviews (CATI, Online): 300+',
    stats: [{ label: 'Interviews', value: '300+' }, { label: 'Business Lines', value: '10+' }, { label: 'Survey Rounds', value: '10+' }, { label: 'Industry Award', value: '1' }],
    challenge: 'The petroleum retail business of a major group needed to assess current satisfaction levels across customer touchpoints and identify key improvement areas.',
    approach: 'A customer relationship assessment program was designed to assess satisfaction levels and identify key strengths and improvement areas. The program has been an annual affair conducted for more than 10 rounds.',
    outcome: 'Clear improvement areas identified for each survey round. The client made changes to further consolidate loyalty — serving as inputs for winning the Dubai Quality Award.',
    clientLogo: '/logos/05_Oil_and_Gas/enoc.png',
  },
  {
    id: 'cs-25',
    sector: 'Oil & Gas',
    image: '/images/case-fuel-station.jpg',
    title: 'Mystery Shopping and Process Compliance Audit for Fuel Stations in UAE',
    geography: 'UAE',
    segment: 'Fuel station staff, Customers',
    methodology: 'Mystery Visits: 100+ · Observation Research',
    stats: [{ label: 'Mystery Visits', value: '100+' }, { label: 'Stations Covered', value: '50+' }, { label: 'KPIs Measured', value: '15+' }, { label: 'Research Waves', value: '4+' }],
    challenge: 'A major petroleum retail company needed to assess compliance with service standards, customer experience, and process adherence across their fuel station network in the UAE.',
    approach: '4BC deployed trained mystery shoppers across fuel stations, evaluating service quality, compliance with operating procedures, cleanliness, and customer interaction standards across multiple waves.',
    outcome: 'The client identified key compliance gaps and service improvement areas, implementing targeted training and operational improvements across their network.',
    clientLogo: '/logos/05_Oil_and_Gas/enoc.png',
  },
  {
    id: 'cs-26',
    sector: 'Oil & Gas',
    image: '/images/case-fuel-oil.jpg',
    title: 'Market Assessment for DGO, Fuel Oil and Bitumen in UAE',
    geography: 'UAE',
    segment: 'Industrial buyers, Logistics companies, Construction firms',
    methodology: 'Qualitative IDIs: 40+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '40+' }, { label: 'Product Categories', value: '3' }, { label: 'Customer Segments', value: '5+' }, { label: 'Market Horizon', value: '5 Yrs' }],
    challenge: 'A major energy company needed to understand the market size, competitive dynamics, and demand drivers for diesel gas oil (DGO), fuel oil, and bitumen in the UAE.',
    approach: 'Expert IDIs with industrial buyers, contractors, and logistics companies combined with secondary analysis to size the market by product type and map competitive activity.',
    outcome: 'The client refined their commercial strategy for these product categories, identifying priority customer segments and channels with the strongest demand potential.',
    clientLogo: null,
  },
  {
    id: 'cs-27',
    sector: 'Oil & Gas',
    image: '/images/case-lubricants.jpg',
    title: 'Market Sizing and Shares for Lubricants in UAE',
    geography: 'UAE',
    segment: 'Distributors, Fleet operators, Workshops',
    methodology: 'Qualitative IDIs: 50+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '50+' }, { label: 'Segments Covered', value: '4' }, { label: 'Brands Tracked', value: '10+' }, { label: 'Market Horizon', value: '5 Yrs' }],
    challenge: 'A major lubricants brand needed a clear picture of market size, competitive landscape, and demand drivers in the UAE to prioritize their commercial investments.',
    approach: 'IDIs with distributors, fleet operators, and workshops combined with secondary data to size the market and estimate brand shares across automotive and industrial lubricant segments.',
    outcome: 'The client reallocated their marketing and distribution investments based on updated market intelligence, targeting the highest-growth sub-categories.',
    clientLogo: '/logos/05_Oil_and_Gas/castrol.jpeg',
  },
  {
    id: 'cs-28',
    sector: 'Oil & Gas',
    image: '/images/case-lpg-propane.jpg',
    title: 'Market Assessment for LPG and Propane Gases in UAE',
    geography: 'UAE',
    segment: 'Residential and commercial consumers, Distributors',
    methodology: 'Qualitative IDIs: 30+ · Quantitative Interviews: 200+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '30+' }, { label: 'Consumer Interviews', value: '200+' }, { label: 'Market Segments', value: '3' }, { label: 'Distribution Channels', value: '4' }],
    challenge: 'A gas distribution company needed to understand the market for LPG and propane across residential and commercial segments in the UAE — sizing demand, mapping the competitive landscape, and understanding pricing dynamics.',
    approach: 'Combined IDIs with distributors and commercial buyers, consumer surveys with residential users, and secondary research to size the market and assess competitive dynamics.',
    outcome: 'The client identified priority segments and channels for growth, and developed a competitive pricing and distribution strategy for the UAE market.',
    clientLogo: '/logos/05_Oil_and_Gas/emirates-gas.png',
  },

  // ── Financial Services ──
  {
    id: 'cs-05',
    sector: 'Government',
    image: '/images/case-remittance.jpg',
    title: 'Market Assessment of Illegal Remittance in Saudi Arabia',
    geography: 'Saudi Arabia',
    segment: 'General consumers (expats)',
    methodology: 'Quantitative Interviews: 500+ · Observation Research · Mystery Visits: 10+',
    stats: [{ label: 'Interviews', value: '500+' }, { label: 'Mystery Visits', value: '10+' }, { label: 'Channels Studied', value: '5+' }, { label: 'Methods Used', value: '3' }],
    challenge: 'A government entity of Saudi Arabia needed to understand the volume of illegal remittance originating from the country.',
    approach: 'In-depth analysis to estimate the market size using extrapolation techniques. Large sample quantitative survey among expats + desk research + qualitative in-depth interviews with key stakeholders.',
    outcome: '4BC recommended the lost opportunity size and measures to curb illegal remittance. The client understood the quantum, value, and modus operandi — and took measures to curb the illegal channel.',
    clientLogo: null,
  },
  {
    id: 'cs-29',
    sector: 'Finance',
    image: '/images/case-banking-voc.jpg',
    title: 'Voice of Customer and Satisfaction Study for Banking Services in UAE',
    geography: 'UAE',
    segment: 'Retail banking customers',
    methodology: 'Quantitative Interviews: 500+ · Online Survey',
    stats: [{ label: 'Interviews', value: '500+' }, { label: 'Banks Benchmarked', value: '5+' }, { label: 'KPIs Measured', value: '20+' }, { label: 'NPS Tracked', value: 'Yes' }],
    challenge: 'A leading UAE bank needed to understand customer satisfaction, NPS, and key drivers of loyalty and attrition across its retail banking services — benchmarked against key competitors.',
    approach: 'Large-sample quantitative research with retail customers to measure satisfaction scores, NPS, and priority areas for service improvement, benchmarked against key competitors.',
    outcome: 'The bank implemented targeted service improvements based on identified pain points, directly improving NPS scores in the following tracking wave.',
    clientLogo: '/logos/02_Banking_and_Finance/adcb.png',
  },
  {
    id: 'cs-30',
    sector: 'Finance',
    image: '/images/case-mobile-money.jpg',
    title: 'Market Research for a Mobile Money Application in UAE',
    geography: 'UAE',
    segment: 'Expats, General consumers',
    methodology: 'Qualitative Focus Groups: 4+ · Quantitative Interviews: 300+',
    stats: [{ label: 'Focus Groups', value: '4+' }, { label: 'Interviews', value: '300+' }, { label: 'Nationalities Covered', value: '6+' }, { label: 'Features Tested', value: '10+' }],
    challenge: 'A fintech startup was developing a mobile money application targeting the UAE\'s large expat community and needed to validate the concept, understand user requirements, and assess competitive positioning.',
    approach: 'Multi-phase research using focus groups to explore needs and reactions to early concepts, followed by quantitative validation to assess demand, feature priorities, and willingness to adopt.',
    outcome: 'The client refined the app\'s feature set, positioning, and go-to-market strategy — enabling a focused launch targeting the highest-propensity segments.',
    clientLogo: null,
  },
  {
    id: 'cs-31',
    sector: 'Finance',
    image: '/images/case-corporate-cards.jpg',
    title: 'Market Sizing and Opportunity Assessment for Corporate Credit Cards Among SMEs',
    geography: 'UAE, Saudi Arabia and Egypt',
    segment: 'SME owners, Finance managers',
    methodology: 'Quantitative Interviews: 600+ · Secondary Research',
    stats: [{ label: 'Interviews', value: '600+' }, { label: 'Markets Covered', value: '3' }, { label: 'SME Segments', value: '4' }, { label: 'Product Features Tested', value: '8+' }],
    challenge: 'A global financial institution needed to assess the opportunity for corporate credit card products targeting the SME segment across three MEA markets.',
    approach: 'Quantitative research with SME decision-makers across UAE, Saudi Arabia, and Egypt to size the opportunity, understand current behavior, and assess demand for new product features.',
    outcome: 'The client prioritized UAE and Saudi Arabia for immediate launch, informed by clear data on opportunity size and the most compelling product propositions for each market.',
    clientLogo: '/logos/02_Banking_and_Finance/american-express.png',
  },
  {
    id: 'cs-32',
    sector: 'Finance',
    image: '/images/case-branch-cx.jpg',
    title: 'Customer Experience Research Across Bank Branches in UAE',
    geography: 'UAE',
    segment: 'Retail banking customers, Branch visitors',
    methodology: 'Mystery Shopping: 100+ · Quantitative Exit Surveys: 500+',
    stats: [{ label: 'Mystery Visits', value: '100+' }, { label: 'Exit Surveys', value: '500+' }, { label: 'Branches Covered', value: '30+' }, { label: 'KPIs Measured', value: '15+' }],
    challenge: 'A retail bank needed to assess the quality of customer experience across their branch network in the UAE — identifying service delivery gaps and benchmarking against competitors.',
    approach: 'Combined mystery shopping across branches with quantitative exit surveys among actual customers to measure both compliance with service standards and genuine customer sentiment.',
    outcome: 'The bank identified specific branches and interaction types needing attention, enabling targeted coaching and operational improvements across the network.',
    clientLogo: '/logos/02_Banking_and_Finance/hsbc.png',
  },
  {
    id: 'cs-33',
    sector: 'Finance',
    image: '/images/case-bank-brand.jpg',
    title: 'Brand Image and Equity Study for a Leading Bank in UAE',
    geography: 'UAE',
    segment: 'General consumers, Business customers',
    methodology: 'Quantitative Interviews: 500+',
    stats: [{ label: 'Interviews', value: '500+' }, { label: 'Brand Attributes', value: '20+' }, { label: 'Consumer Segments', value: '4' }, { label: 'Banks Benchmarked', value: '5+' }],
    challenge: 'A major UAE bank wanted to understand how its brand was perceived relative to competitors — assessing brand equity, key associations, and opportunities to strengthen positioning.',
    approach: 'Quantitative brand equity study among consumers and business customers, measuring awareness, image attributes, brand strength, and competitive differentiation.',
    outcome: 'The client developed a revised brand strategy addressing identified perception gaps, with prioritized messaging and channel investments.',
    clientLogo: '/logos/02_Banking_and_Finance/adcb.png',
  },

  // ── Telecom & ICT ──
  {
    id: 'cs-34',
    sector: 'Telecom',
    image: '/images/case-voip.jpg',
    title: 'Competitive Intelligence on VOIP Calling Services in UAE',
    geography: 'UAE',
    segment: 'SMEs, Individual users',
    methodology: 'Qualitative IDIs: 20+ · Secondary Research · Mystery Calls',
    stats: [{ label: 'Expert IDIs', value: '20+' }, { label: 'Mystery Calls', value: '30+' }, { label: 'Providers Assessed', value: '10+' }, { label: 'Segments Studied', value: '3' }],
    challenge: 'A VOIP services provider needed to understand the competitive landscape in the UAE — mapping competitor offerings, pricing, and positioning among SME and individual user segments.',
    approach: 'Competitive audit using mystery calls and secondary research, supplemented by IDIs with SME users and IT decision-makers to understand usage drivers and switching triggers.',
    outcome: 'The client developed a differentiated positioning strategy and competitive pricing model based on clear data on competitor strengths and market gaps.',
    clientLogo: null,
  },
  {
    id: 'cs-35',
    sector: 'Telecom',
    image: '/images/case-wireless-presentation.jpg',
    title: 'Market Sizing and Demand Estimation for Wireless Presentation Systems in UAE',
    geography: 'UAE',
    segment: 'Corporate businesses, Education institutions',
    methodology: 'Qualitative IDIs: 30+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '30+' }, { label: 'Buyer Segments', value: '3' }, { label: 'Brands Evaluated', value: '8+' }, { label: 'Market Horizon', value: '5 Yrs' }],
    challenge: 'A technology manufacturer needed to understand the market size and demand drivers for wireless presentation systems in the UAE corporate and education sectors.',
    approach: 'Expert IDIs with IT procurement managers and technology buyers across corporates and institutions, combined with secondary research to size the addressable market and map competitive dynamics.',
    outcome: 'The client validated market opportunity and identified the most receptive buyer segments and the optimal channel strategy for the UAE market.',
    clientLogo: null,
  },
  {
    id: 'cs-36',
    sector: 'Telecom',
    image: '/images/case-partner-identification.jpg',
    title: 'Partner Identification and Evaluation for Water Heater Distribution in Egypt',
    geography: 'Egypt',
    segment: 'Distributors, Retailers, Trade partners',
    methodology: 'Qualitative IDIs: 30+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '30+' }, { label: 'Distributors Evaluated', value: '15+' }, { label: 'Regions Covered', value: '3' }, { label: 'Selection Criteria', value: '8+' }],
    challenge: 'An international home appliance manufacturer wanted to identify and evaluate the right distribution partners to enter the Egyptian water heater market effectively.',
    approach: 'Structured qualitative research with potential distributors and retailers across Egypt, assessing capability, market reach, financial stability, and strategic fit — supplemented by secondary research on the competitive landscape.',
    outcome: 'The client selected two preferred distribution partners and entered the Egyptian market with a clearly mapped channel strategy.',
    clientLogo: null,
  },
  {
    id: 'cs-37',
    sector: 'Telecom',
    image: '/images/case-ict-qatar.jpg',
    title: 'ICT Sector Landscape and Usage Study Among SMEs in Qatar',
    geography: 'Qatar',
    segment: 'SMEs, IT decision makers',
    methodology: 'Quantitative Interviews: 300+ · Secondary Research',
    stats: [{ label: 'Interviews', value: '300+' }, { label: 'ICT Categories', value: '8+' }, { label: 'SME Segments', value: '4' }, { label: 'Brands Tracked', value: '15+' }],
    challenge: 'A technology company needed to understand the ICT landscape in Qatar — mapping current usage, purchase behavior, and competitive positioning among the SME segment.',
    approach: 'Quantitative research among IT decision-makers at Qatari SMEs, combined with secondary data analysis to build a comprehensive picture of market dynamics and purchase drivers.',
    outcome: 'The client identified the highest-opportunity product categories and decision-maker segments, enabling a focused sales and marketing approach for the Qatar market.',
    clientLogo: null,
  },
]

export type CaseStudy = typeof caseStudies[0]
