export const sectorConfig: Record<string, { color: string; bg: string; gradient: string; accent: string }> = {
  Retail:        { color: 'text-emerald-700', bg: 'bg-emerald-50 border-emerald-200', gradient: 'from-emerald-600 to-teal-700', accent: '#059669' },
  Finance:       { color: 'text-blue-700',    bg: 'bg-blue-50 border-blue-200',       gradient: 'from-blue-600 to-indigo-700', accent: '#2563EB' },
  'Oil & Gas':   { color: 'text-orange-700',  bg: 'bg-orange-50 border-orange-200',   gradient: 'from-orange-500 to-amber-600', accent: '#D97706' },
  Industrial:    { color: 'text-slate-700',   bg: 'bg-slate-50 border-slate-200',     gradient: 'from-slate-600 to-gray-700', accent: '#475569' },
  Government:    { color: 'text-purple-700',  bg: 'bg-purple-50 border-purple-200',   gradient: 'from-purple-600 to-indigo-700', accent: '#7C3AED' },
  'Real Estate': { color: 'text-amber-700',   bg: 'bg-amber-50 border-amber-200',     gradient: 'from-amber-500 to-orange-600', accent: '#D97706' },
  Transport:     { color: 'text-cyan-700',    bg: 'bg-cyan-50 border-cyan-200',       gradient: 'from-cyan-600 to-blue-700', accent: '#0891B2' },
}

export const caseStudies = [
  {
    id: 'cs-01',
    sector: 'Retail',
    image: '/images/case-retail.jpg',
    title: 'Identifying Potential Locations to Expand a Grocery Store Network',
    geography: 'Dubai and Abu Dhabi, UAE',
    segment: 'Grocery shops, Consumers',
    methodology: 'Qualitative IDIs: 20+ · Quantitative Interviews: 500+ · Secondary research',
    stats: [{ label: 'Interviews', value: '500+' }, { label: 'Cities', value: '2' }, { label: 'Clusters Mapped', value: '40+' }],
    challenge: 'A diversified business group needed to expand their retail operations. Key questions: Which locations are most attractive? How many stores? What store format? What product mix? What is the competitive landscape?',
    approach: '4BC conducted a thorough geo-mapping exercise dividing cities into clusters, plotting retail stores, and understanding the demographic profile of residents and their grocery shopping habits. High-attractiveness clusters were identified using the proprietary 4BC Landscape tool.',
    outcome: 'The client expanded their retail operations across high-attractive clusters across each of the cities, with a data-backed network plan guiding store format and product assortment decisions.',
    clientLogo: '/logos/01_Retail_and_Food/bmmi.png',
  },
  {
    id: 'cs-02',
    sector: 'Transport',
    image: '/images/case-fintech.jpg',
    title: 'Opportunity Assessment of Digitalization of Minibus Taxis in South Africa',
    geography: 'South Africa',
    segment: 'Commuters, Taxi Owners, Taxi Associations, Taxi Financiers',
    methodology: 'Qualitative IDIs: 50+ · Quantitative Interviews: 500+',
    stats: [{ label: 'IDIs Conducted', value: '50+' }, { label: 'Interviews', value: '500+' }, { label: 'Stakeholder Groups', value: '4' }],
    challenge: 'A leading card payment company wanted to develop a solution to digitalize the ticketing system among minibus taxis in South Africa by understanding the opportunity size, drivers, and barriers.',
    approach: '4BC conducted an opportunity sizing analysis by estimating mini-bus taxis operating in South Africa, along with large sample quantitative and qualitative in-depth interviews with drivers, passengers, taxi associations and government authorities.',
    outcome: '4BC recommended a go-to-market strategy based on findings and a phase-wise roll-out plan for successful implementation.',
    clientLogo: '/logos/02_Banking_and_Finance/visa.png',
  },
  {
    id: 'cs-03',
    sector: 'Retail',
    image: '/images/case-retail.jpg',
    title: 'Usage & Attitudes of HORECA Towards Oils in Saudi Arabia',
    geography: 'Saudi Arabia (Riyadh, Jeddah, Dammam)',
    segment: 'HORECA',
    methodology: 'Quantitative Interviews: 300+',
    stats: [{ label: 'Interviews', value: '300+' }, { label: 'Cities', value: '3' }, { label: 'Brands Tracked', value: '10+' }],
    challenge: 'A leading FMCG company needed to develop a successful growth strategy in the HORECA segment by understanding their needs and expectations in the "oil" category.',
    approach: 'Large sample quantitative research across HORECA in Saudi Arabia to understand purchase habits, brand awareness, and sourcing practices across key cities.',
    outcome: 'The client penetrated further into the HORECA segment for oils and fats by offering the right packaging and SKUs, informed by granular demand data.',
    clientLogo: '/logos/01_Retail_and_Food/freshly-foods.png',
  },
  {
    id: 'cs-04',
    sector: 'Industrial',
    image: '/images/hero-professional.jpg',
    title: 'Develop Channel Strategy for a Large Business Group in UAE',
    geography: 'UAE',
    segment: 'Dealers, Consumers',
    methodology: 'Qualitative IDIs: 100+ · Quantitative Interviews: 4,500+ · Secondary Research · Geo-mapping',
    stats: [{ label: 'Expert IDIs', value: '100+' }, { label: 'Interviews', value: '4,500+' }, { label: 'GPS Locations', value: '1,500+' }],
    challenge: 'One of the largest business Groups in UAE wanted to understand the channel network for all its offerings across automobile, industrial equipment, and services.',
    approach: '4BC used the geo-mapping platform to understand demographics, conducted 100+ Expert IDIs, and mapped 1,500+ GPS locations along with comprehensive secondary data to build a full channel intelligence picture.',
    outcome: 'The client developed a 5-year network strategy for their entire portfolio based on the findings.',
    clientLogo: null,
  },
  {
    id: 'cs-05',
    sector: 'Government',
    image: '/images/hero-bg.jpg',
    title: 'Market Assessment of Illegal Remittance in Saudi Arabia',
    geography: 'Saudi Arabia',
    segment: 'General consumers (expats)',
    methodology: 'Quantitative Interviews: 500+ · Observation Research · Mystery Visits: 10+',
    stats: [{ label: 'Interviews', value: '500+' }, { label: 'Mystery Visits', value: '10+' }, { label: 'Channels Studied', value: '5+' }],
    challenge: 'A government entity of Saudi Arabia needed to understand the volume of illegal remittance originating from the country.',
    approach: 'In-depth analysis to estimate the market size using extrapolation techniques. Large sample quantitative survey among expats + desk research + qualitative in-depth interviews with key stakeholders.',
    outcome: '4BC recommended the lost opportunity size and measures to curb illegal remittance. The client understood the quantum, value, and modus operandi — and took measures to curb the illegal channel.',
    clientLogo: null,
  },
  {
    id: 'cs-06',
    sector: 'Industrial',
    image: '/images/hero-professional.jpg',
    title: 'Market Feasibility for Setting Up a Concrete Pipe Manufacturing Unit in Oman',
    geography: 'UAE, Oman and Saudi Arabia',
    segment: 'Manufacturers, EPC Consultants and Contractors',
    methodology: 'Qualitative IDIs: 50+ · Secondary Research',
    stats: [{ label: 'Expert IDIs', value: '50+' }, { label: 'Markets', value: '3' }, { label: 'Pipeline Segments', value: '2' }],
    challenge: 'A large Omani Group needed to understand the market potential for concrete pipe business in Oman and its export opportunity to neighboring countries.',
    approach: '4BC conducted competition landscape, market sizing, market share, and market forecast analysis for sewage pipelines and storm water drainage pipelines.',
    outcome: 'The client started operations of manufacturing concrete pipes in Muscat, Oman, targeting Oman, UAE and Saudi Arabia.',
    clientLogo: '/logos/04_Industrial/amiantit-oman.png',
  },
  {
    id: 'cs-07',
    sector: 'Oil & Gas',
    image: '/images/case-oilgas.jpg',
    title: 'Customer Satisfaction Study for a Major O&G Business in the UAE',
    geography: 'UAE',
    segment: 'Decision makers among customer companies',
    methodology: 'Quantitative Interviews (CATI, Online): 300+',
    stats: [{ label: 'Interviews', value: '300+' }, { label: 'Business Lines', value: '10+' }, { label: 'Survey Rounds', value: '10+' }],
    challenge: 'The petroleum retail business of a major group needed to assess current satisfaction levels across customer touchpoints and identify key improvement areas.',
    approach: 'A customer relationship assessment program was designed to assess satisfaction levels and identify key strengths and improvement areas. The program has been an annual affair conducted for more than 10 rounds.',
    outcome: 'Clear improvement areas identified for each survey round. The client made changes to further consolidate loyalty — serving as inputs for winning the Dubai Quality Award.',
    clientLogo: '/logos/05_Oil_and_Gas/enoc.png',
  },
  {
    id: 'cs-08',
    sector: 'Real Estate',
    image: '/images/hero-bg.jpg',
    title: 'Competitive Market Intelligence Study on Various Free Zones in the UAE',
    geography: 'UAE',
    segment: 'Offices, Industrial Units, Land, Flexi Desk',
    methodology: 'Mystery Calls: 50+ · Secondary Research',
    stats: [{ label: 'Free Zones Studied', value: '15+' }, { label: 'Mystery Calls', value: '50+' }, { label: 'Offer Types', value: '4' }],
    challenge: 'A prominent government-owned free zone authority needed to understand the competition offerings and conduct a benchmarking competitive intelligence study.',
    approach: '4BC conducted desk research along with mystery calls to free zones to understand offerings and prices across all key property categories.',
    outcome: 'The client developed their offerings to be competitive in the local UAE market.',
    clientLogo: '/logos/03_Real_Estate_and_Construction/dmcc.png',
  },
]

export type CaseStudy = typeof caseStudies[0]
