import {
  ShoppingBag, Landmark, Building2, Flame, Factory,
  Truck, Wifi, Shield, Globe, Layers, Package,
  Car, Activity, Zap,
} from 'lucide-react'

export type Sector = {
  slug: string
  name: string
  tagline: string
  description: string
  intro?: string
  whatWeUncover?: { name: string; desc: string }[]
  recentEngagements?: string[]
  engagements: string | null
  research: string
  researchList: string[]
  clients: string
  clientList: string[]
  logoImages: string[]
  engagementsList: string[]
  gradient: string
  gradientFrom: string
  accentHex: string
  icon: React.ElementType
  image?: string
}

export const sectors: Sector[] = [
  {
    slug: 'retail-food',
    name: 'Retail & Food Products',
    tagline: 'Where Consumer Behavior Shifts Fast — And Data Often Doesn\'t Keep Up',
    description: 'We help FMCG and retail brands navigate the complex MEA consumer landscape — from category demand to network expansion and HORECA channel insights.',
    intro: 'The retail landscape in MEA is evolving at unprecedented speed. E-commerce is growing, but traditional trade still dominates in many markets. Expat preferences clash with local tastes. And in categories like FMCG, the difference between a successful launch and a costly failure often comes down to ground-level insight.',
    whatWeUncover: [
      { name: 'Location Intelligence', desc: 'Where to expand? Which clusters offer the highest potential? What\'s the competitive density?' },
      { name: 'Consumer Segmentation', desc: 'Who\'s buying? What drives their choices? How do preferences vary by nationality, income, or urban vs. rural?' },
      { name: 'Channel Strategy', desc: 'Modern trade vs. traditional trade. Online vs. offline. Which mix maximizes reach and margin?' },
      { name: 'Product Optimization', desc: 'Packaging, pricing, assortment. What works in Dubai won\'t necessarily resonate in Jeddah or Nairobi.' },
      { name: 'Competitive Benchmarking', desc: 'Who\'s winning? Why? Where are the white spaces?' },
    ],
    recentEngagements: [
      'UAE: Identified 40+ high-potential clusters for a grocery chain\'s expansion, combining GIS mapping with 500+ consumer interviews across 2 cities.',
      'Saudi Arabia: Assessed HORECA segment attitudes toward cooking oils, tracking 10+ brands across 3 cities with 300+ interviews.',
    ],
    engagements: '50+',
    research: 'Chocolate Spreads, Dressings, Ready-to-eat foods, Frozen foods, HORECA, Beverages, Vegetable oils and fats, Bread improvers',
    researchList: ['Market sizing & opportunity assessment', 'HORECA channel analysis', 'Consumer U&A studies', 'Network & location planning', 'Concept evaluation & NPD'],
    clients: 'Savola · LeSaffre · Nestlé · Unilever · BMMI · LuLu · Freshly Foods · KBBO Group · Nestlé Professional',
    clientList: ['Savola', 'Nestlé', 'Unilever', 'LeSaffre', 'BMMI', 'LuLu', 'Freshly Foods', 'KBBO Group'],
    logoImages: [
      '/logos/01_Retail_and_Food/bmmi.png',
      '/logos/01_Retail_and_Food/lulu.png',
      '/logos/01_Retail_and_Food/freshly-foods.png',
      '/logos/01_Retail_and_Food/lesaffre.png',
      '/logos/01_Retail_and_Food/unilever.jpeg',
      '/logos/01_Retail_and_Food/nestle.png',
      '/logos/01_Retail_and_Food/kbbo-group.png',
      '/logos/01_Retail_and_Food/savola.png',
    ],
    engagementsList: [
      'Market sizing and opportunity assessment of Tea across Egypt and Pakistan',
      'Concept evaluation for plant-based food products in UAE',
      'Need state assessment of salad dressings across HORECA in UAE',
      'Channel research for premium tea across HORECA operators in UAE',
      'Market assessment for ready-to-eat food products in Bahrain',
      'Network planning for opening a new grocery store in UAE',
    ],
    gradient: 'linear-gradient(135deg, #C2410C 0%, #9A1716 100%)',
    gradientFrom: '#C2410C',
    accentHex: '#C2410C',
    icon: ShoppingBag,
    image: '/sectors/retail-food.jpg',
  },
  {
    slug: 'banking-finance',
    name: 'Banking & Finance',
    tagline: 'Trust Is the Real Currency',
    description: 'Supporting banks, insurers, fintech and financial institutions across MEA with deep market intelligence, customer satisfaction programs, and opportunity sizing.',
    intro: 'From Islamic banking to fintech disruption, from expat remittances to SME lending — the financial sector in MEA operates under unique cultural, regulatory, and competitive pressures.',
    whatWeUncover: [
      { name: 'Customer Trust & Perception', desc: 'What drives brand preference? Where are the gaps in service?' },
      { name: 'Digital Adoption Barriers', desc: 'Why do customers still prefer branches in some markets? What would make them switch?' },
      { name: 'Regulatory Navigation', desc: 'How do compliance requirements vary by country? What\'s the real cost of entry?' },
      { name: 'SME & Corporate Banking Needs', desc: 'What do businesses actually want from their financial partners?' },
      { name: 'Remittance & Cross-Border Flows', desc: 'Where is money moving? Why? And how can you capture a share?' },
    ],
    recentEngagements: [
      'South Africa: Evaluated digital payment adoption among minibus taxis, interviewing 500+ drivers and commuters across 4 stakeholder groups.',
      'Saudi Arabia: Assessed illegal remittance flows for a government entity, combining 500+ interviews with 10+ mystery visits across 5+ channels.',
    ],
    engagements: '75+',
    research: 'SME Banking, Corporate Banking, Credit Cards, Corporate Cards, Payment Solutions, Online Trading, Investment, Insurance, Fintech',
    researchList: ['Market opportunity sizing', 'Customer satisfaction & NPS', 'Brand awareness & usage', 'Regulatory landscape analysis', 'Fintech opportunity assessment'],
    clients: 'VISA · ADCB · American Express · Bupa · RSA · UAE Insurance Authority · SABB · Cashee · HSBC · RFIGlobal',
    clientList: ['VISA', 'ADCB', 'American Express', 'Bupa', 'RSA', 'UAE Insurance Authority', 'SABB', 'HSBC', 'Cashee'],
    logoImages: [
      '/logos/02_Banking_and_Finance/visa.png',
      '/logos/02_Banking_and_Finance/rfi-global.png',
      '/logos/02_Banking_and_Finance/hsbc.png',
      '/logos/02_Banking_and_Finance/american-express.png',
      '/logos/02_Banking_and_Finance/adcb.png',
      '/logos/02_Banking_and_Finance/bupa.png',
      '/logos/02_Banking_and_Finance/rsa.png',
      '/logos/02_Banking_and_Finance/uae-insurance-authority.jpeg',
      '/logos/02_Banking_and_Finance/sabb.png',
      '/logos/02_Banking_and_Finance/cashee.png',
    ],
    engagementsList: [
      'Market sizing and opportunity assessment for corporate credit cards across UAE, KSA and Egypt',
      'Brand image and equity study for a leading bank in UAE',
      'Opportunity assessment for digitizing payments across mini-bus taxis in South Africa',
      'Voice of customer and satisfaction with banking services in UAE',
      'Market research for a mobile money application in UAE',
      'Customer experience research across bank branches in UAE',
    ],
    gradient: 'linear-gradient(135deg, #1D4ED8 0%, #1E3A8A 100%)',
    gradientFrom: '#1D4ED8',
    accentHex: '#1D4ED8',
    icon: Landmark,
    image: '/sectors/banking-finance.jpg',
  },
  {
    slug: 'oil-gas',
    name: 'Oil & Gas',
    tagline: 'Where Global Markets Meet Local Realities',
    description: 'Deep sector expertise spanning fuels, lubricants, LPG, environmental services, and industrial utilities — helping energy players understand markets and customers.',
    intro: 'The energy sector in MEA is defined by contrasts: national oil companies with global ambitions, privatization trends in downstream retail, and the urgent push toward sustainability — all while demand patterns shift with economic diversification.',
    whatWeUncover: [
      { name: 'Market Sizing & Strategy', desc: 'Understanding true market opportunity in light of new competition, adoption of alternative fuels, and technological disruption.' },
      { name: 'Customer Journeys & Experience', desc: 'How do purchasing decisions happen? Where are the friction points? How can you optimize the customer experience?' },
      { name: 'Retail Performance & Brand Health', desc: 'Continuous monitoring of outlet performance, customer satisfaction, brand reputation, and social impact through mystery audits and tracking studies.' },
      { name: 'Regulatory & Policy Impact', desc: 'From localization requirements to carbon taxes and energy transition goals, what\'s changing and how should you respond?' },
    ],
    recentEngagements: [
      'UAE: Conducted comprehensive market sizing and strategic analysis for petroleum retail operations, assessing customer journeys, CX optimization, and continuous performance tracking across 300+ interviews and 10+ survey rounds.',
      'UAE: Evaluated competitive positioning and performance metrics through mystery audits and brand reputation studies.',
    ],
    engagements: '60+',
    research: 'LPG, propane, lubricants, diesel, petrol, commercial fuels, biotech, water treatment, environmental dust control, boilers & industrial utilities',
    researchList: ['Market sizing & share analysis', 'Customer satisfaction & NPS', 'Mystery audits', 'Market assessment for new products', 'Demand estimation'],
    clients: 'PDO · Emirates Gas · ENOC · Emarat · Castrol · Shell · Horizon Terminals · GASCO',
    clientList: ['PDO', 'Emirates Gas', 'ENOC', 'Emarat', 'Castrol', 'Shell', 'Horizon Terminals', 'GASCO'],
    logoImages: [
      '/logos/05_Oil_and_Gas/pdo.png',
      '/logos/05_Oil_and_Gas/emirates-gas.png',
      '/logos/05_Oil_and_Gas/enoc.png',
      '/logos/05_Oil_and_Gas/emarat.png',
      '/logos/05_Oil_and_Gas/castrol.jpeg',
      '/logos/05_Oil_and_Gas/shell.png',
      '/logos/05_Oil_and_Gas/horizon-terminals.jpeg',
      '/logos/05_Oil_and_Gas/gasco.png',
    ],
    engagementsList: [
      'Market sizing and shares for lubricants in UAE',
      'Market assessment for LPG and Propane gases for cylinders and bulk gas in UAE',
      'Mystery audits for process compliance for fuel stations in UAE',
      'Customer satisfaction and NPS for commercial fuels, LPG, Lubricants businesses',
    ],
    gradient: 'linear-gradient(135deg, #D97706 0%, #92400E 100%)',
    gradientFrom: '#D97706',
    accentHex: '#D97706',
    icon: Flame,
    image: '/sectors/fuels-energy.jpg',
  },
  {
    slug: 'real-estate',
    name: 'Real Estate & Construction',
    tagline: 'Building for a Population in Flux',
    description: 'From free zone benchmarking to catchment area mapping and mall feasibility — we help real estate developers and construction firms make data-backed decisions.',
    intro: 'From Dubai\'s skyscrapers to Riyadh\'s giga-projects, from affordable housing in Egypt to commercial developments in Nairobi — real estate in MEA is shaped by demographic shifts, expat flows, and rapid urbanization.',
    whatWeUncover: [
      { name: 'Demand Mapping', desc: 'Where is the real need? What\'s oversupplied?' },
      { name: 'Expat vs. Local Preferences', desc: 'How do housing, retail, and office space requirements differ?' },
      { name: 'Regulatory & Zoning Risks', desc: 'What\'s buildable? What\'s not? Where are the hidden costs?' },
      { name: 'Commercial Real Estate Trends', desc: 'How is remote work reshaping office demand? What\'s the future of retail space?' },
      { name: 'Affordable Housing Gaps', desc: 'Where is the unmet need? What models actually work?' },
    ],
    engagements: '30+',
    research: 'Free Zones, Commercial Offices, Malls, Paints, Pipes, Cement, Adhesives, Coatings, Elevators, Construction Materials, Roofing, Insulation, Escalators',
    researchList: ['Competitive intelligence & benchmarking', 'Catchment area assessment', 'Geo-mapping & network planning', 'Feasibility studies', 'Trade flow analysis'],
    clients: 'DP World · DMCC · Emaar · Dubai South · Dubai Airport Freezone · Dubai Development Authority · WJ Towell · Palm Hills · Nakheel · ThyssenKrupp · Al-Futtaim Engineering',
    clientList: ['DP World', 'DMCC', 'Emaar', 'Dubai South', 'Dubai Airport Freezone', 'Nakheel', 'Palm Hills', 'ThyssenKrupp'],
    logoImages: [
      '/logos/03_Real_Estate_and_Construction/emaar.png',
      '/logos/03_Real_Estate_and_Construction/dubai-airport-freezone.jpeg',
      '/logos/03_Real_Estate_and_Construction/dmcc.png',
      '/logos/03_Real_Estate_and_Construction/dubai-south.png',
      '/logos/03_Real_Estate_and_Construction/palm-hills.png',
      '/logos/03_Real_Estate_and_Construction/wj-towell.png',
      '/logos/03_Real_Estate_and_Construction/dp-world.jpeg',
      '/logos/03_Real_Estate_and_Construction/dubai-development-authority.png',
    ],
    engagementsList: [
      'Competitive intelligence and cost benchmarking of free zones in the UAE',
      'Catchment area assessment for developing a new mall in UAE',
      'Campaign recall and effectiveness study for a UAE free zone',
      'Walking habits and pedestrian flow study in Dubai',
      'Growth strategy for building automation solutions in UAE',
      'Opportunity assessment for facility management services in UAE',
    ],
    gradient: 'linear-gradient(135deg, #047857 0%, #065F46 100%)',
    gradientFrom: '#047857',
    accentHex: '#047857',
    icon: Building2,
    image: '/sectors/real-estate.jpg',
  },
  {
    slug: 'government-public-sector',
    name: 'Government & Public Sector',
    tagline: 'Where Policy Meets Practicality',
    description: 'We support government entities, regulators, and public sector stakeholders with policy-relevant research, satisfaction studies, and regulatory landscape analysis.',
    intro: 'Government entities in MEA operate at the intersection of vision and execution — balancing economic diversification, citizen satisfaction, and global competitiveness.',
    whatWeUncover: [
      { name: 'Citizen & Business Satisfaction Studies', desc: 'What\'s working? What\'s not? How can services improve?' },
      { name: 'Economic Impact Assessments', desc: 'What\'s the real effect of policy changes, infrastructure projects, or regulatory shifts?' },
      { name: 'Stakeholder Engagement Strategies', desc: 'How do you align private sector, public sector, and community interests?' },
      { name: 'Benchmarking & Best Practices', desc: 'What can be learned from other markets? What should be avoided?' },
    ],
    recentEngagements: [
      'UAE: Conducted a competitive intelligence study for a free zone authority, evaluating 15+ free zones, 4+ offer types, and competitive positioning through 50+ mystery calls.',
      'Saudi Arabia: Assessed illegal remittance flows to inform policy interventions, combining 500+ interviews with mystery visits and multi-channel analysis.',
    ],
    engagements: null,
    research: 'Regulatory landscapes, policy impact, public service satisfaction, economic impact assessment, illegal market sizing',
    researchList: ['Regulatory landscape analysis', 'Public service satisfaction', 'Policy impact assessment', 'Socio-economic studies', 'Illegal market sizing'],
    clients: 'GACA · mada · Ministry clients',
    clientList: ['GACA', 'mada', 'Ministry clients'],
    logoImages: [],
    engagementsList: [
      'Market assessment of illegal remittance in Saudi Arabia',
      'Satisfaction research for public sector services',
    ],
    gradient: 'linear-gradient(135deg, #3730A3 0%, #1E1B4B 100%)',
    gradientFrom: '#3730A3',
    accentHex: '#3730A3',
    icon: Shield,
    image: '/sectors/government.jpg',
  },
  {
    slug: 'industrial',
    name: 'Industrial & Manufacturing',
    tagline: 'From Local Production to Global Supply Chains',
    description: 'From concrete pipes to decorative paints — we help industrial companies understand demand, size markets, assess feasibility and plan their distribution networks.',
    intro: 'MEA\'s industrial sector is at a crossroads: localization pressures, supply chain diversification, and the push for higher-value manufacturing.',
    whatWeUncover: [
      { name: 'Market Feasibility', desc: 'Is there real demand? What\'s the competitive landscape?' },
      { name: 'Supply Chain Optimization', desc: 'Where are the bottlenecks? How can you reduce dependency risks?' },
      { name: 'Export Potential', desc: 'Which markets offer the best opportunities? What are the barriers?' },
      { name: 'Technology Adoption', desc: 'How can Industry 4.0 improve efficiency, quality, and competitiveness?' },
    ],
    recentEngagements: [
      'Oman: Evaluated market potential for concrete pipes, assessing demand across 2 pipeline segments and export opportunities to GCC neighbors through 50+ expert interviews.',
      'UAE: Mapped distribution networks for a major regional conglomerate\'s industrial equipment and commercial vehicle divisions, conducting 100+ expert IDIs and 4,500+ wider interviews across 1,500+ GPS-mapped locations.',
    ],
    engagements: '50+',
    research: 'Boilers, Water treatment plants, Environmental dust control, Concrete pipes, Decorative paints, Construction equipment, Automotive services',
    researchList: ['Market feasibility studies', 'Market sizing & shares', 'Brand health assessments', 'Network & distribution planning', 'Competitive landscape'],
    clients: 'ThyssenKrupp · Arkan · The Kanoo Group · Thermax · Twiga · Sadolin · Jotun · Amiantit Oman',
    clientList: ['ThyssenKrupp', 'Arkan', 'The Kanoo Group', 'Thermax', 'Twiga', 'Sadolin', 'Jotun', 'Amiantit Oman'],
    logoImages: [
      '/logos/04_Industrial/jotun.png',
      '/logos/04_Industrial/kanoo-group.jpeg',
      '/logos/04_Industrial/arkan.jpeg',
      '/logos/04_Industrial/amiantit-oman.png',
      '/logos/04_Industrial/thyssenkrupp.png',
      '/logos/04_Industrial/sadolin.png',
      '/logos/04_Industrial/twiga.png',
      '/logos/04_Industrial/thermax.png',
    ],
    engagementsList: [
      'Market feasibility for setting up a concrete pipe factory in Oman',
      'Market sizing and shares for decorative paints in Qatar',
      'Brand health assessment for decorative paints in UAE',
      '5-year Network planning for a leading business house into automotive, construction equipment and services',
    ],
    gradient: 'linear-gradient(135deg, #475569 0%, #1E293B 100%)',
    gradientFrom: '#475569',
    accentHex: '#475569',
    icon: Factory,
    image: '/sectors/industrial-manufacturing.jpg',
  },
  {
    slug: 'transport-logistics',
    name: 'Transport & Logistics',
    tagline: 'Moving People, Goods, and Economies',
    description: 'We help logistics and transportation companies understand market dynamics, plan networks, and assess competitive positioning across MEA.',
    intro: 'From Dubai\'s logistics hubs to Africa\'s informal transport networks, mobility is the backbone of MEA\'s economy.',
    whatWeUncover: [
      { name: 'Route & Network Efficiency', desc: 'Where are the gaps? How can you reduce costs?' },
      { name: 'Digital Transformation', desc: 'How can ticketing, tracking, and fleet management be improved?' },
      { name: 'Regulatory & Infrastructure Constraints', desc: 'What\'s holding back efficiency? How can you navigate it?' },
      { name: 'Customer & Stakeholder Needs', desc: 'What do passengers, shippers, and partners really want?' },
    ],
    recentEngagements: [
      'South Africa: Assessed digitalization opportunities for minibus taxis, evaluating opportunity size, drivers, and barriers through 50+ IDIs and 500+ stakeholder interviews.',
    ],
    engagements: '30+',
    research: 'Port intelligence, freight logistics, transport networks, digital ticketing, fleet management',
    researchList: ['Industry landscape studies', 'Competitive intelligence on ports', 'Digital transformation assessment', 'Stakeholder & customer needs', 'Market sizing for logistics'],
    clients: 'DP World · Regional logistics operators',
    clientList: ['DP World'],
    logoImages: [],
    engagementsList: [
      'Competitive intelligence on Ports across Middle East and Africa region',
      'Opportunity assessment for digitizing payments across mini-bus taxis in South Africa',
    ],
    gradient: 'linear-gradient(135deg, #0F766E 0%, #134E4A 100%)',
    gradientFrom: '#0F766E',
    accentHex: '#0F766E',
    icon: Truck,
    image: '/sectors/transport-logistics.jpg',
  },
  {
    slug: 'automotive',
    name: 'Automotive & Commercial Vehicles',
    tagline: 'Navigating Electrification, Localization, and Shifting Customer Preferences',
    description: 'We help manufacturers, distributors, and dealers navigate the MEA automotive sector — from channel strategy and customer preferences to after-sales excellence and market opportunity.',
    intro: 'The automotive sector in MEA is at an inflection point — balancing traditional combustion engines with electrification, managing localization pressures, and understanding how customer expectations are evolving across expat and local segments.',
    whatWeUncover: [
      { name: 'Channel & Distribution Strategy', desc: 'What\'s the optimal network structure? How do you balance direct, franchise, and dealer models?' },
      { name: 'Customer Preferences & Purchasing Behavior', desc: 'What drives vehicle choice? How do preferences vary by segment and geography?' },
      { name: 'After-Sales & Service Excellence', desc: 'How can you optimize the customer experience beyond the sale?' },
      { name: 'Market Opportunity Assessment', desc: 'Where is growth potential? What segments are underserved?' },
    ],
    recentEngagements: [
      'UAE: Developed comprehensive channel strategy for a major regional conglomerate across passenger vehicles and commercial vehicles divisions, mapping distribution networks, customer needs, and growth opportunities through 100+ expert interviews and 4,500+ extended research interviews across 1,500+ GPS-mapped locations.',
    ],
    engagements: '30+',
    research: 'LCV, HCV, Passenger cars, Spare parts, Tyres, Auto components, Connected car services, Dealer networks',
    researchList: ['Dealer network optimization', 'Brand positioning & usage', 'Customer satisfaction & NPS', 'Market sizing for automotive', 'Competitive intelligence'],
    clients: 'Ford · Mercedes · Toyota · Nissan · Audi · Volvo · GM · Renault · Kia · Bridgestone',
    clientList: ['Ford', 'Mercedes', 'Toyota', 'Nissan', 'Audi', 'Volvo', 'GM', 'Renault', 'Kia', 'Bridgestone'],
    logoImages: [
      '/logos/06_Logistics_and_Transportation/ford.png',
      '/logos/06_Logistics_and_Transportation/kia.jpeg',
      '/logos/06_Logistics_and_Transportation/nissan.jpeg',
      '/logos/06_Logistics_and_Transportation/audi.jpeg',
      '/logos/06_Logistics_and_Transportation/mercedes.png',
      '/logos/06_Logistics_and_Transportation/volvo.png',
      '/logos/06_Logistics_and_Transportation/gm.png',
      '/logos/06_Logistics_and_Transportation/renault.jpeg',
      '/logos/06_Logistics_and_Transportation/toyota.jpeg',
      '/logos/06_Logistics_and_Transportation/bridgestone.png',
    ],
    engagementsList: [
      'Industry landscape of used cars in UAE, DRC, Afghanistan and Yemen',
      'Market sizing and dealer optimization for TSR tyres across UAE, Saudi Arabia and Egypt',
      'Brand positioning and usage of connected car services among consumers in UAE and Saudi Arabia',
    ],
    gradient: 'linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)',
    gradientFrom: '#7C3AED',
    accentHex: '#7C3AED',
    icon: Car,
    image: '/sectors/logistics.jpg',
  },
  {
    slug: 'telecom-ict',
    name: 'Telecom & Technology',
    tagline: 'Connecting the Connected — and the Unconnected',
    description: 'Supporting telecom operators, electronics brands, and ICT companies with market sizing, brand studies, and demand estimation across the region.',
    intro: 'From 5G rollouts to fintech adoption, from smart cities to rural connectivity — MEA\'s tech sector is defined by extremes.',
    whatWeUncover: [
      { name: 'Adoption Barriers', desc: 'Why aren\'t customers upgrading? What\'s holding back digital services?' },
      { name: 'Competitive Positioning', desc: 'How do you differentiate in crowded markets?' },
      { name: 'Regulatory Challenges', desc: 'What\'s changing? How can you stay ahead?' },
      { name: 'B2B vs. B2C Dynamics', desc: 'What do enterprises need? How do consumer preferences vary?' },
    ],
    engagements: '50+',
    research: 'VOIP, Wired and Wireless communication, IT industry landscape among SMEs, Wireless presentation systems, Monitors, Home appliances, Printers',
    researchList: ['ICT industry landscape', 'Market sizing & demand estimation', 'Brand positioning studies', 'SME segmentation', 'Competitive intelligence'],
    clients: 'du · Maroc Telecom · Airtel · e& (Etisalat) · Vodafone · Djezzy',
    clientList: ['du', 'Maroc Telecom', 'Airtel', 'e& (Etisalat)', 'Vodafone', 'Djezzy'],
    logoImages: [
      '/logos/07_Telecom_and_ICT/du.png',
      '/logos/07_Telecom_and_ICT/maroc-telecom.png',
      '/logos/08_Extended_Clients/airtel.png',
      '/logos/07_Telecom_and_ICT/etisalat.png',
      '/logos/07_Telecom_and_ICT/vodafone.png',
      '/logos/07_Telecom_and_ICT/djezzy.jpeg',
    ],
    engagementsList: [
      'ICT industry landscape and usage among SMEs in Qatar',
      'Market sizing and demand estimation for wireless presentation systems in UAE',
      'Brand positioning and usage of printers among SMEs in UAE',
      'Competitive intelligence on VOIP services in UAE',
    ],
    gradient: 'linear-gradient(135deg, #0891B2 0%, #1E40AF 100%)',
    gradientFrom: '#0891B2',
    accentHex: '#0891B2',
    icon: Wifi,
    image: '/sectors/telecom.jpg',
  },
  {
    slug: 'fmcg-cpg',
    name: 'FMCG & Consumer Goods',
    tagline: 'Winning the Daily Battle for Shelf Space and Mindshare',
    description: 'Supporting leading FMCG and CPG companies with consumer insights, brand tracking, and market sizing across Middle East and Africa.',
    intro: 'In MEA\'s FMCG sector, success comes down to understanding the nuances — expat vs. local tastes, modern trade vs. traditional retail, and the role of culture in purchasing decisions.',
    whatWeUncover: [
      { name: 'Category Growth Drivers', desc: 'What\'s shaping demand? Where are the white spaces?' },
      { name: 'Retailer & Distributor Dynamics', desc: 'Who controls the shelf? How do you influence them?' },
      { name: 'Packaging & Positioning', desc: 'What resonates? What doesn\'t?' },
      { name: 'Promotion Effectiveness', desc: 'What works in Ramadan? During summer? In different cities?' },
    ],
    recentEngagements: [
      'Saudi Arabia: Studied HORECA segment attitudes toward cooking oils, tracking 10+ brands across 3 cities with 300+ interviews.',
    ],
    engagements: '100+',
    research: 'Consumer goods, packaged foods, personal care, household products across MEA',
    researchList: ['Consumer U&A studies', 'Brand health tracking', 'Market sizing', 'NPD concept evaluation', 'Shopper intelligence'],
    clients: 'Unilever · Nestlé · Savola · KBBO Group',
    clientList: ['Unilever', 'Nestlé', 'Savola', 'KBBO Group'],
    logoImages: [],
    engagementsList: [
      'Usage & attitudes research for oils and fats across HORECA in Saudi Arabia',
      'Brand health study for a leading FMCG company across UAE and KSA',
    ],
    gradient: 'linear-gradient(135deg, #DB2777 0%, #9D174D 100%)',
    gradientFrom: '#DB2777',
    accentHex: '#DB2777',
    icon: Package,
    image: '/sectors/fmcg-cpg.jpg',
  },
  {
    slug: 'healthcare-pharma',
    name: 'Healthcare & Pharmaceuticals',
    tagline: 'Navigating Regulation, Trust, and Rapid Change',
    description: 'From public health initiatives to private hospital expansions, we help healthcare and pharma clients navigate MEA\'s complex regulatory, cultural, and infrastructure landscape.',
    intro: 'From public health initiatives to private hospital expansions, MEA\'s healthcare sector is complex — shaped by regulation, cultural attitudes, and varying levels of infrastructure.',
    whatWeUncover: [
      { name: 'Patient & Provider Needs', desc: 'What\'s missing? Where are the gaps?' },
      { name: 'Regulatory Pathways', desc: 'How do you navigate approvals, pricing, and market access?' },
      { name: 'Digital Health Adoption', desc: 'What\'s the real potential for telemedicine, e-pharmacies, and healthtech?' },
      { name: 'Pharma Distribution Challenges', desc: 'How do you reach patients effectively?' },
    ],
    engagements: null,
    research: 'Hospitals, clinics, pharmacies, medical devices, telemedicine, health insurance, pharma distribution',
    researchList: ['Patient & provider satisfaction', 'Regulatory landscape analysis', 'Digital health adoption', 'Market sizing & opportunity', 'Distribution channel mapping'],
    clients: '',
    clientList: [],
    logoImages: [],
    engagementsList: [],
    gradient: 'linear-gradient(135deg, #0E7490 0%, #164E63 100%)',
    gradientFrom: '#0E7490',
    accentHex: '#0E7490',
    icon: Activity,
    image: '/sectors/healthcare-pharma.jpg',
  },
  {
    slug: 'energy-utilities',
    name: 'Energy & Utilities',
    tagline: 'Powering Growth in a Changing Landscape',
    description: 'From renewables to water scarcity and electricity demand — we help energy and utility clients navigate MEA\'s evolving market landscape.',
    intro: 'From oil and gas to renewables, from water scarcity to electricity demand — energy is the lifeblood of MEA\'s economies.',
    whatWeUncover: [
      { name: 'Market Entry Strategies', desc: 'Where are the opportunities? What are the risks?' },
      { name: 'Regulatory & Policy Shifts', desc: 'How will carbon taxes, localization, and sustainability goals impact your business?' },
      { name: 'Customer & Industrial Demand', desc: 'What\'s driving consumption? How can you capture share?' },
      { name: 'Renewable Energy Feasibility', desc: 'What\'s the real potential? What are the barriers?' },
    ],
    engagements: null,
    research: 'Renewables, solar, wind, electricity distribution, water utilities, sustainability strategy',
    researchList: ['Market entry strategy', 'Regulatory & policy impact', 'Demand estimation', 'Renewable energy feasibility', 'Competitive landscape'],
    clients: '',
    clientList: [],
    logoImages: [],
    engagementsList: [],
    gradient: 'linear-gradient(135deg, #15803D 0%, #14532D 100%)',
    gradientFrom: '#15803D',
    accentHex: '#15803D',
    icon: Zap,
    image: '/sectors/fuels-energy.jpg',
  },
  {
    slug: 'regional-conglomerates',
    name: 'Regional Conglomerates',
    tagline: 'Multi-sector advisory for the region\'s largest business groups.',
    description: 'Large regional business groups trust us for multi-sector intelligence, network planning, and strategic advisory across their diverse portfolios.',
    engagements: null,
    research: 'Multi-sector advisory for large regional business groups',
    researchList: ['Multi-sector market intelligence', 'Portfolio opportunity assessment', 'Network planning', 'Competitive benchmarking', 'Strategic advisory'],
    clients: 'Abdul Latif Jameel · JK Cement · Alghanim · Al-Futtaim Group',
    clientList: ['Abdul Latif Jameel', 'JK Cement', 'Alghanim', 'Al-Futtaim Group'],
    logoImages: ['/logos/al-futtaim.png'],
    engagementsList: [
      'Develop channel strategy for a large business group across automobile, industrial equipment and services in UAE',
    ],
    gradient: 'linear-gradient(135deg, #059669 0%, #064E3B 100%)',
    gradientFrom: '#059669',
    accentHex: '#059669',
    icon: Globe,
    image: '/sectors/regional-conglomerates.jpg',
  },
  {
    slug: 'metals-industries',
    name: 'Metal & Core Industries',
    tagline: 'Market intelligence for the backbone of MEA industry.',
    description: 'Steel, aluminium, construction inputs — we provide market sizing, competitive intelligence, and feasibility studies for core industrial players.',
    engagements: null,
    research: 'Steel, aluminium, construction materials, raw industrial inputs',
    researchList: ['Market sizing', 'Competitive intelligence', 'Feasibility studies', 'Supply & demand analysis'],
    clients: '',
    clientList: [],
    logoImages: [],
    engagementsList: [],
    gradient: 'linear-gradient(135deg, #64748B 0%, #334155 100%)',
    gradientFrom: '#64748B',
    accentHex: '#64748B',
    icon: Layers,
    image: '/sectors/metal-core.jpg',
  },
]

export function getSectorBySlug(slug: string): Sector | undefined {
  return sectors.find((s) => s.slug === slug)
}
