import {
  ShoppingBag, Landmark, Building2, Flame, Factory,
  Truck, Wifi, Shield, Globe, Layers, Package,
} from 'lucide-react'

export type Sector = {
  slug: string
  name: string
  tagline: string
  description: string
  engagements: string | null
  research: string
  researchList: string[]
  clients: string
  clientList: string[]
  logoImages: string[]    // paths relative to /public
  engagementsList: string[]
  gradient: string        // CSS gradient string
  gradientFrom: string    // tailwind-safe hex for overlay
  accentHex: string       // button / badge color
  icon: React.ElementType
  image?: string          // path relative to /public
}

export const sectors: Sector[] = [
  {
    slug: 'retail-food',
    name: 'Retail & Food Products',
    tagline: 'From shelf to strategy — understanding MEA consumer behaviour.',
    description: 'We help FMCG and retail brands navigate the complex MEA consumer landscape — from category demand to network expansion and HORECA channel insights.',
    engagements: '50+',
    research: 'Chocolate Spreads, Dressings, Ready-to-eat foods, Frozen foods, HORECA, Beverages, Vegetable oils and fats, Bread improvers',
    researchList: ['Market sizing & opportunity assessment', 'HORECA channel analysis', 'Consumer U&A studies', 'Network & location planning', 'Concept evaluation & NPD'],
    clients: 'Savola · LeSaffre · Nestlé · Unilever · BMMI · LuLu · Freshly Foods · KBBO Group · Nestlé Professional',
    clientList: ['Savola', 'Nestlé', 'Unilever', 'LeSaffre', 'BMMI', 'LuLu', 'Freshly Foods', 'KBBO Group'],
    logoImages: [
      '/logos/01_Retail_and_Food/bmmi.png',
      '/logos/01_Retail_and_Food/lulu.png',
      '/logos/01_Retail_and_Food/freshly-foods.png',
      '/logos/01_Retail_and_Food/lesaffre.png',
      '/logos/01_Retail_and_Food/unilever.jpeg',
      '/logos/01_Retail_and_Food/nestle.png',
      '/logos/01_Retail_and_Food/kbbo-group.png',
      '/logos/01_Retail_and_Food/savola.png',
    ],
    engagementsList: [
      'Market sizing and opportunity assessment of Tea across Egypt and Pakistan',
      'Concept evaluation for Chocolate Spread across HORECA in UAE and Saudi Arabia',
      'Need state assessment of salad dressings across HORECA in UAE',
      'Network planning for opening a new grocery store in UAE',
    ],
    gradient: 'linear-gradient(135deg, #C2410C 0%, #9A1716 100%)',
    gradientFrom: '#C2410C',
    accentHex: '#C2410C',
    icon: ShoppingBag,
    image: '/sectors/retail-food.jpg',
  },
  {
    slug: 'banking-finance',
    name: 'Banking & Finance',
    tagline: 'Intelligence that moves financial markets forward.',
    description: 'Supporting banks, insurers, fintech and financial institutions across MEA with deep market intelligence, customer satisfaction programs, and opportunity sizing.',
    engagements: '75+',
    research: 'SME Banking, Corporate Banking, Credit Cards, Corporate Cards, Payment Solutions, Online Trading, Investment, Insurance, Fintech',
    researchList: ['Market opportunity sizing', 'Customer satisfaction & NPS', 'Brand awareness & usage', 'Regulatory landscape analysis', 'Fintech opportunity assessment'],
    clients: 'VISA · ADCB · American Express · Bupa · RSA · UAE Insurance Authority · SABB · Cashee · HSBC · RFIGlobal',
    clientList: ['VISA', 'ADCB', 'American Express', 'Bupa', 'RSA', 'UAE Insurance Authority', 'SABB', 'HSBC', 'Cashee'],
    logoImages: [
      '/logos/02_Banking_and_Finance/visa.png',
      '/logos/02_Banking_and_Finance/rfi-global.png',
      '/logos/02_Banking_and_Finance/hsbc.png',
      '/logos/02_Banking_and_Finance/american-express.png',
      '/logos/02_Banking_and_Finance/adcb.png',
      '/logos/02_Banking_and_Finance/bupa.png',
      '/logos/02_Banking_and_Finance/rsa.png',
      '/logos/02_Banking_and_Finance/uae-insurance-authority.jpeg',
      '/logos/02_Banking_and_Finance/sabb.png',
      '/logos/02_Banking_and_Finance/cashee.png',
    ],
    engagementsList: [
      'Market sizing and opportunity assessment for corporate credit cards across UAE and Egypt',
      'Brand awareness and usage of medical insurance among consumers in UAE',
      'Opportunity assessment for digitizing payments across mini-bus taxis in South Africa',
      'Voice of customers and satisfaction with banking services in UAE',
    ],
    gradient: 'linear-gradient(135deg, #1D4ED8 0%, #1E3A8A 100%)',
    gradientFrom: '#1D4ED8',
    accentHex: '#1D4ED8',
    icon: Landmark,
    image: '/sectors/banking-finance.jpg',
  },
  {
    slug: 'real-estate',
    name: 'Real Estate & Construction',
    tagline: 'Location intelligence for the region\'s fastest-growing sector.',
    description: 'From free zone benchmarking to catchment area mapping and mall feasibility — we help real estate developers and construction firms make data-backed decisions.',
    engagements: '30+',
    research: 'Free Zones, Commercial Offices, Malls, Paints, Pipes, Cement, Adhesives, Coatings, Elevators, Construction Materials, Roofing, Insulation, Escalators',
    researchList: ['Competitive intelligence & benchmarking', 'Catchment area assessment', 'Geo-mapping & network planning', 'Feasibility studies', 'Trade flow analysis'],
    clients: 'DP World · DMCC · Emaar · Dubai South · Dubai Airport Freezone · Dubai Development Authority · WJ Towell · Palm Hills · Nakheel · ThyssenKrupp · Al-Futtaim Engineering',
    clientList: ['DP World', 'DMCC', 'Emaar', 'Dubai South', 'Dubai Airport Freezone', 'Nakheel', 'Palm Hills', 'ThyssenKrupp'],
    logoImages: [
      '/logos/03_Real_Estate_and_Construction/emaar.png',
      '/logos/03_Real_Estate_and_Construction/dubai-airport-freezone.jpeg',
      '/logos/03_Real_Estate_and_Construction/dmcc.png',
      '/logos/03_Real_Estate_and_Construction/dubai-south.png',
      '/logos/03_Real_Estate_and_Construction/palm-hills.png',
      '/logos/03_Real_Estate_and_Construction/wj-towell.png',
      '/logos/03_Real_Estate_and_Construction/dp-world.jpeg',
      '/logos/03_Real_Estate_and_Construction/dubai-development-authority.png',
    ],
    engagementsList: [
      'Competitive intelligence and cost benchmarking of free zones in the UAE',
      'Catchment area assessment for developing a new mall in UAE',
      'Opportunity assessment for facility management services in UAE',
      'Understanding trade flow within Dubai Fruit and Vegetable Market',
    ],
    gradient: 'linear-gradient(135deg, #047857 0%, #065F46 100%)',
    gradientFrom: '#047857',
    accentHex: '#047857',
    icon: Building2,
    image: '/sectors/real-estate.jpg',
  },
  {
    slug: 'energy-environment',
    name: 'Fuels, Energy & Environment',
    tagline: 'Powering strategic decisions in the region\'s energy sector.',
    description: 'Deep sector expertise spanning fuels, lubricants, LPG, environmental services, and industrial utilities — helping energy players understand markets and customers.',
    engagements: '60+',
    research: 'LPG, propane, lubricants, diesel, petrol, commercial fuels, biotech, water treatment, environmental dust control, boilers & industrial utilities',
    researchList: ['Market sizing & share analysis', 'Customer satisfaction & NPS', 'Mystery audits', 'Market assessment for new products', 'Demand estimation'],
    clients: 'PDO · Emirates Gas · ENOC · Emarat · Castrol · Shell · Horizon Terminals · GASCO',
    clientList: ['PDO', 'Emirates Gas', 'ENOC', 'Emarat', 'Castrol', 'Shell', 'Horizon Terminals', 'GASCO'],
    logoImages: [
      '/logos/05_Oil_and_Gas/pdo.png',
      '/logos/05_Oil_and_Gas/emirates-gas.png',
      '/logos/05_Oil_and_Gas/enoc.png',
      '/logos/05_Oil_and_Gas/emarat.png',
      '/logos/05_Oil_and_Gas/castrol.jpeg',
      '/logos/05_Oil_and_Gas/shell.png',
      '/logos/05_Oil_and_Gas/horizon-terminals.jpeg',
      '/logos/05_Oil_and_Gas/gasco.png',
    ],
    engagementsList: [
      'Market sizing and shares for lubricants in UAE',
      'Market assessment for LPG and Propane gases for cylinders and bulk gas in UAE',
      'Mystery audits for process compliance for fuel stations in UAE',
      'Customer satisfaction and NPS for commercial fuels, LPG, Lubricants businesses',
    ],
    gradient: 'linear-gradient(135deg, #D97706 0%, #92400E 100%)',
    gradientFrom: '#D97706',
    accentHex: '#D97706',
    icon: Flame,
    image: '/sectors/fuels-energy.jpg',
  },
  {
    slug: 'industrial',
    name: 'Industrial',
    tagline: 'Sizing markets and mapping channels across heavy industry.',
    description: 'From concrete pipes to decorative paints — we help industrial companies understand demand, size markets, assess feasibility and plan their distribution networks.',
    engagements: '50+',
    research: 'Boilers, Water treatment plants, Environmental dust control, Concrete pipes, Decorative paints, Construction equipment, Automotive services',
    researchList: ['Market feasibility studies', 'Market sizing & shares', 'Brand health assessments', 'Network & distribution planning', 'Competitive landscape'],
    clients: 'ThyssenKrupp · Arkan · The Kanoo Group · Thermax · Twiga · Sadolin · Jotun · Amiantit Oman',
    clientList: ['ThyssenKrupp', 'Arkan', 'The Kanoo Group', 'Thermax', 'Twiga', 'Sadolin', 'Jotun', 'Amiantit Oman'],
    logoImages: [
      '/logos/04_Industrial/jotun.png',
      '/logos/04_Industrial/kanoo-group.jpeg',
      '/logos/04_Industrial/arkan.jpeg',
      '/logos/04_Industrial/amiantit-oman.png',
      '/logos/04_Industrial/thyssenkrupp.png',
      '/logos/04_Industrial/sadolin.png',
      '/logos/04_Industrial/twiga.png',
      '/logos/04_Industrial/thermax.png',
    ],
    engagementsList: [
      'Market feasibility for setting up a concrete pipe factory in Oman',
      'Market sizing and shares for decorative paints in Qatar',
      'Brand health assessment for decorative paints in UAE',
      '5-year Network planning for a leading business house into automotive, construction equipment and services',
    ],
    gradient: 'linear-gradient(135deg, #475569 0%, #1E293B 100%)',
    gradientFrom: '#475569',
    accentHex: '#475569',
    icon: Factory,
    image: '/sectors/industrial.jpg',
  },
  {
    slug: 'logistics-transportation',
    name: 'Logistics & Transportation',
    tagline: 'From port intelligence to automotive dealer networks.',
    description: 'We help logistics, automotive, and transportation companies understand market dynamics, plan dealer networks, and assess competitive positioning across MEA.',
    engagements: '30+',
    research: 'LCV, HCV, Passenger cars, Spare parts, Tyres, Auto components, Port intelligence, Connected car services',
    researchList: ['Industry landscape studies', 'Dealer network optimization', 'Brand positioning', 'Competitive intelligence on ports', 'Market sizing for automotive'],
    clients: 'Ford · Mercedes · Toyota · Nissan · Audi · Volvo · GM · Renault · Kia · Bridgestone',
    clientList: ['Ford', 'Mercedes', 'Toyota', 'Nissan', 'Audi', 'Volvo', 'GM', 'Renault', 'Kia', 'Bridgestone'],
    logoImages: [
      '/logos/06_Logistics_and_Transportation/bridgestone.png',
      '/logos/06_Logistics_and_Transportation/ford.png',
      '/logos/06_Logistics_and_Transportation/kia.jpeg',
      '/logos/06_Logistics_and_Transportation/nissan.jpeg',
      '/logos/06_Logistics_and_Transportation/audi.jpeg',
      '/logos/06_Logistics_and_Transportation/mercedes.png',
      '/logos/06_Logistics_and_Transportation/volvo.png',
      '/logos/06_Logistics_and_Transportation/gm.png',
      '/logos/06_Logistics_and_Transportation/renault.jpeg',
      '/logos/06_Logistics_and_Transportation/toyota.jpeg',
    ],
    engagementsList: [
      'Industry landscape of used cars in UAE, DRC, Afghanistan and Yemen',
      'Market sizing and dealer optimization for TSR tyres across UAE, Saudi Arabia and Egypt',
      'Brand positioning and usage of connected car services among consumers in UAE and Saudi Arabia',
      'Competitive intelligence on Ports across Middle East and Africa region',
    ],
    gradient: 'linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)',
    gradientFrom: '#7C3AED',
    accentHex: '#7C3AED',
    icon: Truck,
    image: '/sectors/logistics.jpg',
  },
  {
    slug: 'telecom-ict',
    name: 'Telecom & ICT',
    tagline: 'Mapping demand and competition in MEA\'s digital economy.',
    description: 'Supporting telecom operators, electronics brands, and ICT companies with market sizing, brand studies, and demand estimation across the region.',
    engagements: '50+',
    research: 'VOIP, Wired and Wireless communication, IT industry landscape among SMEs, Wireless presentation systems, Monitors, Home appliances, Printers',
    researchList: ['ICT industry landscape', 'Market sizing & demand estimation', 'Brand positioning studies', 'SME segmentation', 'Competitive intelligence'],
    clients: 'du · Maroc Telecom · Airtel · e& (Etisalat) · Vodafone · Djezzy',
    clientList: ['du', 'Maroc Telecom', 'Airtel', 'e& (Etisalat)', 'Vodafone', 'Djezzy'],
    logoImages: [
      '/logos/07_Telecom_and_ICT/du.png',
      '/logos/07_Telecom_and_ICT/maroc-telecom.png',
      '/logos/08_Extended_Clients/airtel.png',
      '/logos/07_Telecom_and_ICT/etisalat.png',
      '/logos/07_Telecom_and_ICT/vodafone.png',
      '/logos/07_Telecom_and_ICT/djezzy.jpeg',
    ],
    engagementsList: [
      'ICT industry landscape and usage among SMEs in Qatar',
      'Market sizing and demand estimation for wireless presentation systems in UAE',
      'Brand positioning and usage of printers among SMEs in UAE',
      'Competitive intelligence on VOIP services in UAE',
    ],
    gradient: 'linear-gradient(135deg, #0891B2 0%, #1E40AF 100%)',
    gradientFrom: '#0891B2',
    accentHex: '#0891B2',
    icon: Wifi,
    image: '/sectors/telecom.jpg',
  },
  {
    slug: 'government-education',
    name: 'Government & Regulators',
    tagline: 'Evidence-based intelligence for public sector decisions.',
    description: 'We support government entities, regulators, and education sector stakeholders with policy-relevant research, satisfaction studies, and regulatory landscape analysis.',
    engagements: null,
    research: 'Regulatory landscapes, policy impact, public service satisfaction, education sector demand',
    researchList: ['Regulatory landscape analysis', 'Public service satisfaction', 'Policy impact assessment', 'Socio-economic studies', 'Illegal market sizing'],
    clients: 'GACA · mada · Ministry clients',
    clientList: ['GACA', 'mada', 'Ministry clients'],
    logoImages: [],
    engagementsList: [
      'Market assessment of illegal remittance in Saudi Arabia',
      'Satisfaction research for public sector services',
    ],
    gradient: 'linear-gradient(135deg, #3730A3 0%, #1E1B4B 100%)',
    gradientFrom: '#3730A3',
    accentHex: '#3730A3',
    icon: Shield,
    image: '/sectors/government.jpg',
  },
  {
    slug: 'regional-conglomerates',
    name: 'Regional Conglomerates',
    tagline: 'Multi-sector advisory for the region\'s largest business groups.',
    description: 'Large regional business groups trust us for multi-sector intelligence, network planning, and strategic advisory across their diverse portfolios.',
    engagements: null,
    research: 'Multi-sector advisory for large regional business groups',
    researchList: ['Multi-sector market intelligence', 'Portfolio opportunity assessment', 'Network planning', 'Competitive benchmarking', 'Strategic advisory'],
    clients: 'Abdul Latif Jameel · JK Cement · Alghanim · Al-Futtaim Group',
    clientList: ['Abdul Latif Jameel', 'JK Cement', 'Alghanim', 'Al-Futtaim Group'],
    logoImages: [],
    engagementsList: [
      'Develop channel strategy for a large business group across automobile, industrial equipment and services in UAE',
    ],
    gradient: 'linear-gradient(135deg, #059669 0%, #064E3B 100%)',
    gradientFrom: '#059669',
    accentHex: '#059669',
    icon: Globe,
    image: '/sectors/regional-conglomerates.jpg',
  },
  {
    slug: 'metals-industries',
    name: 'Metal & Core Industries',
    tagline: 'Market intelligence for the backbone of MEA industry.',
    description: 'Steel, aluminium, construction inputs — we provide market sizing, competitive intelligence, and feasibility studies for core industrial players.',
    engagements: null,
    research: 'Steel, aluminium, construction materials, raw industrial inputs',
    researchList: ['Market sizing', 'Competitive intelligence', 'Feasibility studies', 'Supply & demand analysis'],
    clients: '',
    clientList: [],
    logoImages: [],
    engagementsList: [],
    gradient: 'linear-gradient(135deg, #64748B 0%, #334155 100%)',
    gradientFrom: '#64748B',
    accentHex: '#64748B',
    icon: Layers,
    image: '/sectors/metal-core.jpg',
  },
  {
    slug: 'fmcg-cpg',
    name: 'FMCG / CPG',
    tagline: 'Consumer intelligence at scale across MEA markets.',
    description: 'Supporting leading FMCG and CPG companies with consumer insights, brand tracking, and market sizing across Middle East and Africa.',
    engagements: '100+',
    research: 'Consumer goods, packaged foods, personal care, household products across MEA',
    researchList: ['Consumer U&A studies', 'Brand health tracking', 'Market sizing', 'NPD concept evaluation', 'Shopper intelligence'],
    clients: 'Unilever · Nestlé · Savola · KBBO Group',
    clientList: ['Unilever', 'Nestlé', 'Savola', 'KBBO Group'],
    logoImages: [],
    engagementsList: [
      'Usage & attitudes research for oils and fats across HORECA in Saudi Arabia',
      'Brand health study for a leading FMCG company across UAE and KSA',
    ],
    gradient: 'linear-gradient(135deg, #DB2777 0%, #9D174D 100%)',
    gradientFrom: '#DB2777',
    accentHex: '#DB2777',
    icon: Package,
    image: '/sectors/fmcg-cpg.jpg',
  },
]

export function getSectorBySlug(slug: string): Sector | undefined {
  return sectors.find((s) => s.slug === slug)
}
